version: '2'
services:
    diabetesfollowup-app:
        image: diabetesfollowup
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://diabetesfollowup-mysql:3306/diabetesfollowup?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    diabetesfollowup-mysql:
        extends:
            file: mysql.yml
            service: diabetesfollowup-mysql
